language: python
sudo: false
python:
    - 3.8
env:
    - TEST_DIR=python-project-lvl1
    - TEST_DIR=python-project-lvl2
before_install:
- pip install poetry
install:
- sh -c 'cd $TEST_DIR && make install'
script:
- sh -c 'cd $TEST_DIR && make lint'
- sh -c 'cd $TEST_DIR && make test'
